### ISSUE TITLE
Corregir ayuda en nombre de campo de texto corto

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#101]
Corregir ayuda en nombre de campo de texto corto incluyendo tildes

**Comment by rafaelposadaf** [comment]
Corregir tildes en las ayudas (campo de texto corto)de: 
Peso(Posición), 
Ancho (código), 
Campo de solo lectura (modificación), 
Id html(ejecución), 
Valor predeterminado (contravía, sesión), 
Texto para el place holder(aparecerá, vacío, guía, allí)
Campo de solo lectura(útil, modificación)
Titulo de ayuda(descripción)

**Comment by unix4you2** [comment]
Hecho.  703b56987adc0ea0f82b85c9c6038137560f68ee
