### ISSUE TITLE
Agregar cargar informe en informes

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#104]
Cuando estoy en los informes. Agregar la opción en los tipos de acción para cargar otro informe. ya que para poder hacerlo debo agregar varios comandos. Agregando esta opción solo tendría que indicarle que informe cargar y ya.

**Comment by unix4you2** [comment]
Finalizado.  e004c41b2e3f75f6570f3f4db8830e466ced4e91
