### ISSUE TITLE
Poner una imagen pequeña al frente de cada formulario para mostrar los eventos

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#108]
En la ficha de formularios, al frente de cada uno, agregar una imagen(de pequeña como un boton) que al pasar el mouse, aparezca un tooltip con cada uno de los eventos que contiene ese formulario.

**Comment by unix4you2** [comment]
Finalizado sobre los botones de evento de cada control para evitar tener que ingresar a la edición de cada uno.  1cfb5886f09ca2969506ff097e94dc48f3384d65
