### ISSUE TITLE
Crear una opción en javascript para las opciones de menu

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#112]
Cuando se esta creando una opción de menu, agregar la opción como en los formualrios e informes de poder ejecutar métodos en javascript (verificar si es útil)

**Comment by unix4you2** [comment]
La opción ya existe.  Simplemente debe dirigirse a la opción de creación de menúes y en la sección de "Destino" indicar en lugar de una URL el comando en Javascript que desea correr mediante el formato compatible con los HREF tradicionales  **javascript:sucomando('sus parametros');**
