### ISSUE TITLE
Habilitar la opción para documentar código

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#116]
Documentar eventos o archivos javascript desde Practico con el formato inicialmente de naturaldocs (al momento de crearlos  que aparezca una documentación como plantilla para cambiarla). Para que el desarrollador no tenga que estar copiando el formato.

Esta documentación puede ser una opción desde que se crea el proyecto para que aparezca siempre en los métodos y cambiable desde la configuración principal

**Comment by unix4you2** [comment]
Finalizado.  Commit: 67c0fb9051b7d93fe6adaf9820669e558f5845a7
