### ISSUE TITLE
Agregar información del campo cuando pasa el mouse por encima

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#118]
Agregar un botón como de información al lado del de eliminar o en algún otro lado, donde en el tooltip aparezca información relacionada a ese campo como (id_html,campo manualmente, valor predeterminado, validación de datos?)

**Comment by unix4you2** [comment]
Finalizado.  Commit 1e5ac30dc5c40f871ae721996c12399678831517
