### ISSUE TITLE
Agregar id_html dentro de la ventana de los eventos

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#126]
Cuando quiero agregar un evento y me abre la ventana para establecerlo, a veces no recuerdo que id_html lleva ese campo, seria chevere poder contar con el id dentro de la ventana de los eventos para no ir a buscar ese id en otro lado.

**Comment by unix4you2** [comment]
Finalizado.  Commit:  e3b3abf6b750d216c50a98b1aa8081dd7e7776b7
