### ISSUE TITLE
Agregar tipo de informe Grafico/Tabla en la lista de informes

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#127]
En mis informes no puedo diferenciar entre un gráfico o una tabla a menos que le ponga un nombre en el informe, seria mas cómodo poder contar con ese columna para poderlos diferenciar.

**Comment by unix4you2** [comment]
Finalizado.  Commit: 31aaa733207ee4fb4dbe23a10be9f1af40ded258
