### ISSUE TITLE
Cuando se clonen los inf/frm crear boton para ir a ese elemento creado

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#128]
Cuando se clonan los frm/inf cuando aparece el boton con el id de creado siempre va directamente al frm/inf respectivo. Seria interesante que hayan dos botones uno para ir a frm/inf y otro para ir a al objeto copiado.

**Comment by unix4you2** [comment]
Finalizado dentro de las copias masivas.  Commit:  e40934a007bea3c0381a789c444d2b3b952c98d7
