### ISSUE TITLE
Agregar nombre o id del inf/frm en Diseño general de campos

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#132]
Cuando estoy en Diseño general de campos y tengo varios inf/frm tengo que analizar mucho a veces que inf/frm es cual, seria util poder saber que inf/frm es. Poniendo el nombre o id en el titulo de Diseño general de campos

**Comment by unix4you2** [comment]
Finalizado.  Commit:  e3dea11e47ff597ea96a1cfca6c6af32261f6842
