### ISSUE TITLE
Cambiar presentacion de informes en formularios

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#139]
Cuando voy a agregar un informe en un informe:
Seria mas cómodo para un usuario cuando agrega un informe a un formulario que pueda escribir el numero del informe y este automaticamente se seleccione.
Esto en teoría se puede solucionar quitando (id. XXX) y dejando solo el XXX. para que cuando seleccione el informe y digite el numero se pueda seleccionar rápidamente

**Comment by unix4you2** [comment]
Finalizado.  Commit f6d1274ac1b54d98ac5c5965a9c25be4c8c69d3a
