### ISSUE TITLE
Agregar id en los informes embebidos de los formularios

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#141]
Esto seria muy útil cuando estoy en un formulario y quiero ir a hacer cambios en la base de datos, ya que de lo contrario tendria que hacer mas pasos para obtener el id de ese informe

**Comment by unix4you2** [comment]
Finalizado.  Commit 9f1ee9b8a34e8cd9b677b289c3502ddb2c38b9e0
