### ISSUE TITLE
Estoy instalandolo con php7.0 y mysql-5.7 y da problemas con la sintaxis de sql que tienes en el instalador. Alguna sugerencia?

### ISSUE THREAD

**Issue by mikethewolf83** [unix4you2/practico#143]

**Comment by unix4you2** [comment]
Puedes regalarnos la descripción del error específico?

A partir de MySQL 5.7 cambiaron algunos detalles en motor y pasaron a ser más estrictos en las especificaciones de llaves y otros campos, esto generalmente es configurable desde tu my.cnf

Tal vez por ahí esté la causa; pero regálame detalles del error para ver si puedo apoyar.

**Comment by mikethewolf83** [comment]
En el practico.mysql en:
DROP TABLE IF EXISTS core_parametros;
CREATE TABLE core_parametros (
  id int(10) NOT NULL AUTO_INCREMENT,
...
  version varchar(20),
...

Puse como valor 30 y funciona, luego cuando trato de crear un formulario me da el siguiente error:

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'practico.core_formulario_objeto.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by<br><b>Detalles</b>: SELECT id,tipo,titulo,campo,ayuda_titulo,ayuda_texto,formulario,peso,columna,obligatorio,visible,valor_predeterminado,validacion_datos,etiqueta_busqueda,ajax_busqueda,valor_unico,solo_lectura,ancho,alto,barra_herramientas,fila_unica,lista_opciones,origen_lista_opciones,origen_lista_valores,valor_etiqueta,url_iframe,objeto_en_ventana,informe_vinculado,maxima_longitud,valor_minimo,valor_maximo,valor_salto,formato_salida,plantilla_archivo,peso_archivo,tamano_pincel,color_trazo,formulario_vinculado,formulario_campo_vinculo,formulario_campo_foraneo,condicion_filtrado_listas,pestana_objeto,personalizacion_tag,modo_inline,imagen,tipo_accion,accion_usuario,valor_check_activo,valor_check_inactivo,valor_placeholder,ocultar_etiqueta,id_html,validacion_extras,clase_contenedor FROM core_formulario_objeto WHERE formulario='3' AND visible=1 GROUP BY pestana_objeto ORDER BY pestana_objeto<br><b>Archivo</b>: /var/www/html/practico/core/comunes.php -> 2638
