### ISSUE TITLE
Agregar titulo de Ancho y Longitud máxima en Agregar un elemento al formulario

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#144]
Cuando estoy agregando o editando un elemento y quiero agregarle una longitud al campo, mucha veces no recuerdo en donde va esa longitud, ya que hay dos campos que por defecto cargan en 0 y no dejan ver cual es cual, entonces para conocer cual de estos dos es, hay que borrar el 0 (por defecto) para saber donde debo agregarlo. Seria muy útil el título de estos campos para no tener que demorarme en encontrar cual es longitud y cual es ancho.

**Comment by unix4you2** [comment]
Finalizado.  Commit 051909a89fe8ab6c149e5254d2fb91c27e2b08b6
