### ISSUE TITLE
Problema en la instalación

### ISSUE THREAD

**Issue by juagon** [unix4you2/practico#177]
Buenas tardes
Al instalar practico 22.1 o 21.7 en xampp (8.0.12) sobre windows 10, el sistema muestra una pantalla en blanco sin ningún error, no logro visualizar algún error en los log.
Gracias por su valiosa orientación

**Comment by unix4you2** [comment]
Hola @juagon 
Dentro de core/configuracion.php podrías habilitar sólo temporalmente una variable ModoDepuracion en valor 1  y de esa manera ver mensajes extendidos para saber por qué tu instalación no te deja seguir adelante. 
 
https://github.com/unix4you2/practico/blob/master/core/configuracion.php#L86

**Comment by juagon** [comment]
Hola Johh gracias por su respuesta

El archivo configuracion.php se encuentra en la
ruta /practico21/mod/pbrowser/core/ puse la variable ModoDepuracion pero
sigue mostrando en blanco la pantalla sin mas errores extendidos en los
logs.

 $PCO_PBROWSER_StandAlone=0; //1=StandAlone 0=Modulo de Practico

        $ZonaHoraria='America/Bogota';
        $IdiomaPredeterminado='es';
        $CodigoGoogleAnalytics='UA-847800-9';
        $ModoDepuracion=1

Muchas gracias por su apoyo

**Comment by unix4you2** [comment]
Hola, no es ese el archivo.  Es el que te puse en la respuesta anterior y se encuentra directamente sobre la raíz /core.  Un ejemplo del mismo lo puedes ver en el enlace.

**Comment by juagon** [comment]
Puede existir entonces un problema que el archivo descargado directamente
desde la página practico-22.1 y practico-21.7 no contengan este archivo ?

O se debe descargar directamente desde el Github ?
