### ISSUE TITLE
[ERROR] Tablero Kanban

### ISSUE THREAD

**Issue by jaimeaba3** [unix4you2/practico#21]
**Describa el error**
Al seleccionar en la pestaña Usuario y permisos la opción Usuarios con posibilidad de edición y/o archivado:
No habilita el botón para archivar.

**Cómo reproducirlo**
Indique el paso a paso que se debe hacer para reproducir este error:
1. Vaya a la opción Crear tarea en Kanban
2. Haga clic en en la pestaña Usuario y permisos
3. Clic en opción Usuarios con posibilidad de edición y/o archivado
4. Al actualizar el tablero no carga botón de archivar.

**Comment by unix4you2** [comment]
Gracias por reportar.
Corregido en commit ef58fa5e5a5f891959efe8f9df99caf8353cb9e2
