### ISSUE TITLE
Recordar Contraseña

### ISSUE THREAD

**Issue by robisagi** [unix4you2/practico#27]
Seria bueno implementar el famoso "Se me olvido la contraseña".
Versión 15.1 Act 14

**Comment by unix4you2** [comment]
Saludos Robin.

De hecho no sé si te has pegado una pasada por el código /core/comunes.php línea 1492.  Ya se está empezando a agregar esta funcionalidad.  Tanto para recordar contraseña como para permitir autoregistro.

```html
<div class="row">
    <div class="col-md-6">
        <a class="btn btn-xs">
            <i class="typcn fa typcn-user-add"></i>
            <?php echo $MULTILANG_Registrarme; ?>
        </a>
    </div>
    <div class="col-md-6">
        <a class="btn btn-xs">
            <i class="fa fa-unlock-alt"></i>
            <?php echo $MULTILANG_OlvideClave; ?>
        </a>
    </div>
</div>
```
Cualquier aporte o pullrequest al respecto es bien recibido.

**Comment by robisagi** [comment]
Excelente.

**Comment by unix4you2** [comment]
Cualquier PullRequest es bienvenido. ;-)
