### ISSUE TITLE
Error en Informes

### ISSUE THREAD

**Issue by robisagi** [unix4you2/practico#28]
En la parte  "Agregar un nuevo campo al informe" 
Específicamente en el campo de Alias, Permite poner caracteres especiales tildes, eñes, pero al ver la vista Previa o el formulario en el usuario genera el siguiente error.
Versión 15.1 Act 14 
Ej:
"Error en tiempo de ejecucion
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '�o FROM app_usuario,core_usuario WHERE app_usuario.identificacion = core_usuar' at line 1
Detalles: SELECT app_usuario.identificacion as Identificacion,app_usuario.nombres as Nombres,app_usuario.apellidos as Apellidos,app_usuario.telefono_fijo as niño FROM app_usuario,core_usuario WHERE app_usuario.identificacion = core_usuario.login"

**Comment by unix4you2** [comment]
Saludos.

Si bien Práctico te permite la construcción de las sentencias de manera visual, sí debemos tener en cuenta los principios básicos para nombrar campos, aliases y demás variables.   Sólo en las etiquetas o labels que son la parte visual hacia el usuario se permiten acentos, eñes y demás.

Para el resto de campos debes conservar la notación de variables como en cualquier lenguaje.

Lo que podemos hacer es tal vez restringir lo que allí se escribe en futuros releases.

**Comment by robisagi** [comment]
ok.

**Comment by unix4you2** [comment]
No sé si fui del todo claro...

```sql
SELECT app_usuario.identificacion as Identificacion,
app_usuario.nombres as Nombres,
app_usuario.apellidos as Apellidos,
app_usuario.telefono_fijo as niño 
FROM app_usuario,core_usuario 
WHERE app_usuario.identificacion = core_usuario.login
```

En realidad si tomas la sentencia que has introducido en Práctico y la ejecutas en cualquier motor obtendrás el mismo error, debido a que el alias **"niño"** es algo no válido en el lenguaje SQL.

Saludos.

**Comment by robisagi** [comment]
Si, es muy claro.

La otra seria un proceso en el cual tu pongas los alias controlados y al retornar la consulta al informe ponerle la que el usuario pidió.
ej
SELECT app_usuario.identificacion as tmp1,
app_usuario.nombres as tmp2,
app_usuario.apellidos as tmp3,
app_usuario.telefono_fijo as tmp4
FROM app_usuario,core_usuario 
WHERE app_usuario.identificacion = core_usuario.login

**Comment by unix4you2** [comment]
:+1:
