### ISSUE TITLE
Guardar script?

### ISSUE THREAD

**Issue by cfb95** [unix4you2/practico#29]
En la pantalla de edición de scripts en edición de formularios,
botón "Editar scripts (avanzado)"
 no tengo la opción de guardar, solo cerrar. No se guardan los cambios.
Alguna idea?

![image](https://cloud.githubusercontent.com/assets/3757912/5866383/7b273c38-a26f-11e4-9cb2-b84580b7dbcb.png)

**Comment by unix4you2** [comment]
Así es!  :)

Los scripts hacen parte de los formularios.  Es por eso que sólo aparece la opción de Cerrar, porque luego deberás hacer clic en actualizar el formulario para que tome los cambios en los scripts.

Saludos

**Comment by cfb95** [comment]
Muchas gracias, 
también intente eso pero no consigo que guarde los cambios, después de presionar el botón actualizar, los cambios desaparecen. Disculpa que insista, pero me interesa mucho poder usarlo!

**Comment by unix4you2** [comment]
Hola Christian.

Prueba poniendo algo simple, digamos un comentario
```javascript
//prueba
```
Luego haz clic en cerrar y luego en el botón de actualizar formulario.   Revisa nuevamente si te ha guardado sin problema el script.

Si aún así no te guarda entonces sigues con los problemas en tu base de datos.  Si te guarda correctamente entonces fue que dentro del script agregaste algún caracter inusual o de escape.  Recuerda que cualquier cadena debe ir encerrada con el tipo de comillas que se indican.

Saludos.

**Comment by cfb95** [comment]
Gracias,
Esa fue exactamente la prueba que hice, agregar un comentario en el autorun y no lo guardo.
voy a probar reinstalando todo desde cero...

**Comment by unix4you2** [comment]
:-1: Me tienen inquieto tantos errores que presentas en almacenamiento sobre el motor.
Todavía tengo la instancia virtualizada de SuSE 13.2+Maria
Por qué no me regalas un backup de la BD yo lo restablezco en ese sistema para ver si tienes algo particular?
También probaré de manera rápida todas las funcionalidades sobre esa distro.
Saludos.

**Comment by cfb95** [comment]
No te preocupes, soy propenso a generar errores!!!
Y tampoco son urgentes las cosas que escribo, tómalo como de ultima prioridad, solo estoy probando la herramienta.
Acabo de volver a probar paso a paso desde cero y borrando la base de datos vieja.
Inicialmente, al instalar sin parches GUARDA los scripts,
Solo después de aplicar el parche 11 deja de guardarlos...

**Comment by unix4you2** [comment]
Ahhh OK :+1: 

**Entonces la cosa es sencilla**

Seguramente el problema lo está generando el editor ACE que fue implementado para poder editar cualquier tipo de archivo y lenguaje sobre esa parte de Práctico.

Simplemente puedes ir a /inc y renombrar la carpeta ace por otro nombre, digamos ace_old  y con eso Práctico dejará de utilizar el editor ampliado y te dejará los scripts como un textarea más sencillo.   Es más simple esa forma pero también más segura.

Prueba eso y me cuentas.  Estaré revisando si es un bug derivado de ese editor y si algo lo actualizamos en el release de febrero.

Saludos!!!

PD.: No me lo tomo como preocupación. Es apoyo y a la vez realimentación para continuar mejorando la herramienta.

**Comment by cfb95** [comment]
Si! renombrando la carpeta ACE guarda los scripts sin problemas! Gracias!

**Comment by unix4you2** [comment]
OK. Marcado como error y en progreso para revisarlo en el lanzamiento que viene.

**Comment by robisagi** [comment]
También me  Paso Igual, renombre  la carpeta "ace" y me dejo guardar.
Version 15.1 update 14

**Comment by unix4you2** [comment]
Saludos!.  Acaba de ser liberada una actualización (015) que corrige esto.

Se puede aplicar el parche de actualización y luego devolver la carpeta **ace** a su nombre original en caso que la hayan renombrado.

**Comment by cfb95** [comment]
Descargado, instalado y probado! Muchas gracias!
