### ISSUE TITLE
Carga de datos

### ISSUE THREAD

**Issue by robisagi** [unix4you2/practico#30]
Seria bueno implementar un formulario en el cual se seleccione un archivo con algún formato y se llene la tabla que se seleccione  igualmente.
Versión 15.1 Act 14

**Comment by unix4you2** [comment]
Saludos.

La actualización 013 de la versión 15.5 permite esta funcionalidad, importando scripts directamente sobre la base de datos e incluso varias tablas al tiempo.

Recordar actualizar de manera incremental a cada versión lanzada en caso de seguir todavía con la 15.1 hasta llegar a la 15.5, luego aplicar el parche 013.

**Comment by unix4you2** [comment]
Editado:  El parche 013 en realidad ha sido cambiado al parche de actualización a la versión 15.6
