### ISSUE TITLE
Consulta de Formularios.

### ISSUE THREAD

**Issue by robisagi** [unix4you2/practico#31]
Buenas tardes doctor Jhon.
La ubicación de los campos en el formulario esta dado por Peso y columna, esto funciona perfecto siempre y cuando todas las filas tengan el mismo numero de campos, pero cuando tengo filas que utilizan menos campos que las demás filas ya se descuadra el formulario.
Trate de poner un campo con la propiedad de Visible = NO pero debe estar amarrado a un campo de la BD y no me deja ponerlo.
Me podrías decir como hacer que puedan conservar la posición XY.

PD: Puede ser desconocimiento mio..apenas estoy conociendo esta SUPER HERRAMIENTA.
Version 15.1 Update 14

Gracias.

**Comment by unix4you2** [comment]
Saludos.
Ese es el comportamiento normal se manejan las filas independientes por cada columna.

Si por algún motivo necesitas equilibrar o poner a igual altura diferentes controles de formulario en diferentes columnas entonces podrías hacer uso de un objeto de etiqueta HTML insertado en el formulario mediante una fila única y los demás elementos con un peso superior a éste.

Esto te consumirá un poco de espacio horizontal pero es la forma en que practicó podría dividir el formulario en varias partes, ya que con la inserción de cualquier objeto con propiedad de fila única práctico genera una nueva disposición de tablas para empezar a ubicar los elementos dentro del formulario.
