### ISSUE TITLE
Mejora para Informes

### ISSUE THREAD

**Issue by rbeltranlopez** [unix4you2/practico#32]
Es posible añadir al práctico DataTables para la presentación de los informes y además para incluir dentro de los mismos filtros de búsqueda, así se evita tener que pasar por formularios y definir solo un campo de filtro, además se aprovecha la funcionalidad de DataTables.

**Comment by unix4you2** [comment]
Saludos Ricardo.

Los DataTables ya están incluídos dentro de los archivos desplegados en la versión 15.1 para permitir paginación de resultados en los informes, filtro por campos, ordenamiento por determinadas columnas y búsquedas en caliente.  Sin embargo no han sido agregados como una opción visual para ser escogida al momento del diseño.

Existen muchas personalizaciones posibles derivadas de la implementación de BootStrap; pero obviamente su inclusión la hacemos de manera gradual.

Cualquier PullRequest que tengas adelantando esto es bienvenido.

Saludos!

**Comment by unix4you2** [comment]
Workaround:

```
    <script language="JavaScript">
        //Carga las tablas en formato DataTable
        $(document).ready(function() {
            <?php
                //Desglosa la cadena de posibles tablas con formato DataTable y las convierte
                $TablasDataTable=@explode("|",$PCO_InformesDataTable);
                for ($i=0; $i<count($TablasDataTable);$i++)
                    echo '$("#'.$TablasDataTable[$i].'").dataTable();';
            ?>
        });
    </script>
```

Este opera sin problemas después de agregar un ID a cada informe, pero igual debe tener una bandera de aplicación pues generaría incompatibilidades con los botones de acción por registro, y obviamente estos últimos son mucho mas útiles que una opción de filtro, ordenamiento y paginación.  ;-)
