### ISSUE TITLE
Validación de la actualización de datos de administrador

### ISSUE THREAD

**Issue by jonshez** [unix4you2/practico#49]
Verificar el proceso de actualización del usuario administrador debido a que cuando se actualiza, el símbolo de respuesta sale en color rojo y con un pulgar hacia abajo, pensaría yo que debe ser un pulgar hacia arriba.

Practico 15.2

**Comment by unix4you2** [comment]
Agregado al form de confirmación:
```
<input type="Hidden" name="PCO_ErrorIcono" value="fa-thumbs-o-up">
<input type="Hidden" name="PCO_ErrorEstilo" value="alert-info">
```
Gracias por el comentario.

**Comment by unix4you2** [comment]
Close #49
