### ISSUE TITLE
El color y signo de mensaje de retorno esta invertido

### ISSUE THREAD

**Issue by jonshez** [unix4you2/practico#52]
Saludos

Se realiza guardado de dato correctamente en un formulario y el sistema me entrega en rojo y con dedo a bajo la respuesta del guardado. Se verifica y el sistema guardo correctamente el dato

Feliz noche

**Comment by unix4you2** [comment]
Saludos.
No es que esté invertido, sino que por defecto ese es el estilo predeterminado pies la función fue generada para presentar mensajes de error.

Si se desea cambiar el estilo e icono del mensaje de retorno entonces se debe utilizar los dos campos de personalización ubicados más abajo durante la creación del botón.

En ellos se puede especificar esos parámetros de apariencia.
