### ISSUE TITLE
rellenar un combo box con otro combo box

### ISSUE THREAD

**Issue by djmcit** [unix4you2/practico#63]

**Comment by unix4you2** [comment]
Saludos @djmcit , 

No eres claro en cuál es el problema...  De todas formas recuerda que para lo que comentas existen ya algunas funciones que hacen el trabajo por ti: 

- PCOJS_ActualizarComboBox(ObjetoListaOpciones)
- PCOJS_LimpiarComboBox(ObjetoListaOpciones)
- PCOJS_AgregarOpcionComboBox(ObjetoListaOpciones,ValorOpcion,EtiquetaOpcion)
- PCOJS_OpcionesCombo_DesdeCSV(ObjetoListaOpciones,Cadena,SeparadorLineas)

Este canal es para reportar fallos de aplicación, si tienes inquietudes por favor coméntalas a través del [grupo de google](https://groups.google.com/forum/#!forum/practicodev).

Saludos.
