### ISSUE TITLE
inhabilitar el "Agregar un agrupador de expresiones o un operador lógico"

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#78]
inhabilitar el "Agregar un agrupador de expresiones o un operador lógico" en los informes cuando se este creando una condición, ya que esta opcion debe ser adicionada sin ninguna condición arriba ingresada

Cuando se digite algo en las condiciones principales(de arriba) deshabilitar(solo lectura) el campo: "inhabilitar el "Agregar un agrupador de expresiones o un operador lógico" y viceversa
![ptco](https://cloud.githubusercontent.com/assets/26600606/24675423/b5709d3c-1944-11e7-8f81-e3c38c5b9450.jpg)
.

**Comment by unix4you2** [comment]
Solved. Commit:  https://github.com/unix4you2/practico/commit/0902c1fefa93b4b7d259cf26b6dec8d554a5dcf3
