### ISSUE TITLE
Agregar ayuda para: Nombre RAD

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#86]
Cuando se este creando por primera vez el proyecto y en la configuración general de práctico agregar ayuda en el campo de 'Nombre RAD', para que el administrador del proyecto conozca para que se va a utilizar ese nombre en su aplicación.

**Comment by unix4you2** [comment]
Finalizado.  Commit:  77af0e414d14fa0a694ac31acaa5747b93ff564c
