### ISSUE TITLE
Enviar el parámetro event desde función javascript

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#88]
Enviar el parámetro event desde cualquier función en javascript de Practico. Así como cuando se crean las funciones en .net (Windows forms), él automaticamente captura el evento y lo pone entre las variables de entrada del método, estas quedan disponibles para el usuario.

**Comment by unix4you2** [comment]
Esto no es necesario.

Si se desea capturar el evento dentro del método o función se puede hacer uso de la siguiente instrucción:
`var evento = PCOJS_Evento || window.event;`
