### ISSUE TITLE
Cargar informes con order by embebido

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#89]
Siempre que se carga un informe, el datatable (si esta habilitado) ordena el primer campo de forma ascendente (independientemente de como se haya ordenado la consulta). Si la consulta ya viene con ese order by con ese primer campo cargaría un poco mas rápido. Esa primera columna seria el primer campo del informe sin ocultar. 
Seria para agregar un order by embebido de practico para que automáticamente siempre en cualquier informe lo organice ascendentemente por el primer campo visible de la consulta.

**Comment by rafaelposadaf** [comment]
Agregar una opción en el datatable para que ordene los informes de acuerdo a un campo específico

**Comment by unix4you2** [comment]
Se ha revisado funcionalidad y se encuentra operando con normalidad.   Algún caso puntual para poder reproducir el escenario?
Saludos.

**Comment by unix4you2** [comment]
Finalizado.  Commit e20ac039d453dfcfc4eb8cd905c4189b16462c52
