### ISSUE TITLE
Establecer en informes cantidad de filas datatable

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#90]
Desde los informes poder establecer el número de filas iniciales que quiero que me aparezcan en el datatable. Incluso poder cambiar los valores por defecto del datatable [10,20,50,100], que el usuario sea el que defina de a cuantas filas quiere que le aparezca en el informe.

**Comment by unix4you2** [comment]
Finalizado.  0edcd2e861111efa66c57d539d3ba6c1a1303063
