### ISSUE TITLE
Mostrar id en los formularios y/o informes en modo edición

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#91]
Cuando cargan los formularios o informes no podemos ver en cual id estamos trabajando. Esto implica que cuando necesitemos conocer el id (en caso de ir a buscar algún registro en la base de datos) tengamos que abrir frm/inf y buscarlo. Con el id en alguna parte del frm/inf podría simplificar mucho las cosas.

**Comment by unix4you2** [comment]
Finalizado.  Commit: 041e55774ac8e5b81f7d9abbf033b391e4dc67b5
