### ISSUE TITLE
Cambiar nombre de "Actualizar formularios"

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#95]
Cuando estamos en modo edición de un formulario y queremos que tome los cambios realizados. hacemos click en un botón llamado "Actualizar formularios", Cambiarlo por "Actualizar formulario" (quitar la s al final).

Seria fantástico un botón al lado de este que diga algo como "Actualizar e ir a escritorio" o "Actualizar e ir a formularios".

**Comment by unix4you2** [comment]
No será agregada la cadena.

En muchas partes del framework se reutilizan palabras desde un léxico general para poder generar aplicaciones multi-idioma.   En este caso se están uniendo dos palabras  "Actualizar" y "Formularios" que ya están en la aplicación.

A menos que se genere una frase nueva para este fin no será reemplazado, ya que implica hacer crecer los archivos de idioma.   Se aceptan pull requests.
