### ISSUE TITLE
Corregir tooltip de campo obligatorio

### ISSUE THREAD

**Issue by rafaelposadaf** [unix4you2/practico#96]
Actualmente en el campo obligatorio dice: <b>"Este campo ha sido marcado como obligatorio.  Si no se ingresa un valor para éste el sistema no almacenará el registro ingresado por el usuario"</b>. Sabemos que si no se ingresa un valor, el sistema no dejará continuar si no se ingresa un valor válido.

**Comment by unix4you2** [comment]
Finalizado.  Commit 5d18e7fcdb4dbc75a4476c445d8cb4ff76cadcf4
